version: '3.8'

# Services
services:

  # PHP Service
  php:
    build:
      dockerfile: php/Dockerfile
    volumes:
      - '../src:/var/www/html'
    depends_on:
      - mariadb

  # Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal
    links:
      - 'php'
    volumes:
      - "../src:/var/www/html"
      - "./nginx/conf:/etc/nginx/conf.d"
      - "./nginx/logs:/var/log/nginx/"
    depends_on:
      - php

  # MariaDB Service
  mariadb:
    image: mariadb:10.9
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mariadb/data:/var/lib/mysql

#  # phpMyAdmin Service
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:latest
#    ports:
#      - 8080:80
#    environment:
#      PMA_HOST: mariadb
#    depends_on:
#      - mariadb

# Volumes
volumes:
  mysqldata:

# Networks
networks:
  internal:
    driver: bridge