version: '3.8'

# Services
services:

  # PHP Service
  php:
    build:
      context: ./services/php
      dockerfile: Dockerfile
    container_name: LaravelDevPhp
    working_dir: /var/www/html
    volumes:
      - '../src:/var/www/html'
    depends_on:
      - mariadb

  # Nginx Service
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    container_name: LaravelDevNginx
    ports:
      - "8080:80"
      - "8443:443"
    #networks:
    #  - internal
    links:
      - 'php'
    volumes:
      - "../src:/var/www/html"
      #- "./nginx/logs:/var/log/nginx/"
      #- "./nginx/ssl:/etc/nginx/ssl"
    depends_on:
      - php

  # MariaDB Service
  mariadb:
    image: mariadb:10.9
    container_name: LaravelDevMariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    #networks:
    #  - internal
    volumes:
      - './volumes/mysql:/var/lib/mysql'

  # Caching
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - './volumes/redis:/data'
    #networks:
    #  - internal

  # Mailing Server
  mailhog:
    image: mailhog/mailhog:latest
    tty: true
    ports:
      - "8025:8025"
      - "1025:1025"
    #networks:
    #  - internal

# Networks
#networks:
#  internal:
#    driver: bridge