version: '3.8'

# Services
services:

  # PHP Service
  php:
    #build:
    #  context: ./services/php
    #  dockerfile: Dockerfile
    image: nntuan/php83node21:latest
    container_name: LaravelDevPhp
    working_dir: /var/www/html
    volumes:
      - '../src:/var/www/html'
    links:
      - 'mariadb'
      - 'redis'
      - 'mailhog'
    depends_on:
      - mariadb
      - redis
      - mailhog

  # Nginx Service
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    container_name: LaravelDevNginx
    ports:
      - "8080:80"
      - "8443:443"
    links:
      - 'php'
    volumes:
      - "../src:/var/www/html"
      - "./volumes/logs/nginx:/var/log/nginx/"
    depends_on:
      - php

  # MariaDB Service
  mariadb:
    image: mariadb:latest
    container_name: LaravelDevMariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - './volumes/mysql:/var/lib/mysql'

  # Caching
  redis:
    image: redis:latest
    container_name: LaravelDevRedis
    ports:
      - "6380:6379"
    volumes:
      - './volumes/redis:/data'

  # Mailing Server
  mailhog:
    image: mailhog/mailhog:latest
    container_name: LaravelDevMailhog
    tty: true
    ports:
      - "8030:8025"
      - "1030:1025"
